### ISSUE TITLE
2023 Custom Design (Accept Multiple Assignes)

### ISSUE THREAD

**Issue by lmas3009** [lmas3009/design2code2live#216] opened 2023-10-07 13:49 UTC
Create the folder based on your project name.

Choose any single-page web designs from dribble/google/Pinterest/etc...

Built it using HTML, CSS/Tailwind CSS, Javascript

Join https://discord.gg/C3PAvsmrKV for fast-updated

Optional: Make it Responsive

Resources
fonts: https://fonts.google.com/
colors: https://coolors.co/
images: https://unsplash.com/ or https://www.pexels.com/

**Comment by zainbinfurqan** [comment] 2023-10-07 13:50
@lmas3009 can i work on this issue?

**Comment by swetha-Kesara** [comment] 2023-10-07 14:08
@lmas3009 Hi, please let me know if the issue is available. I am interested in trying to complete it.

**Comment by harrishDev** [comment] 2023-10-07 14:16
@lmas3009 assign me i'll come up with good looking landing page

**Comment by lmas3009** [comment] 2023-10-07 14:28
sure @zainbinfurqan @swetha-Kesara @harrishDev You can work.

Make sure you have a unique folder names

**Comment by Ramiz1336** [comment] 2023-10-07 14:31
I would like to work on this issue

**Comment by lmas3009** [comment] 2023-10-07 14:43
sure @Ramiz1336

**Comment by priyanshu-gupta0503** [comment] 2023-10-09 03:14
hey@lmas3009  Would like to work on this pls assign this to me.

**Comment by lmas3009** [comment] 2023-10-09 03:30
Sure @priyanshu-gupta0503

**Comment by zainbinfurqan** [comment] 2023-10-10 16:03
@lmas3009  can you review my PR please

**Comment by siddhant2002** [comment] 2023-10-16 10:24
Can I work under this issue?

**Comment by siddhant2002** [comment] 2023-10-18 04:44
Can I work under this issue?

**Comment by lmas3009** [comment] 2023-10-18 05:44
@siddhant2002 you are already assigned

**Comment by AryanSaxenaa** [comment] 2023-10-18 11:21
Hey @lmas3009 , Please assign this issue to me, I am interested in this.

**Comment by siddhant2002** [comment] 2023-10-19 18:17
Raised pr #232 . @lmas3009 Please check the pr.

**Comment by Shreyaprasad02** [comment] 2023-10-23 05:21
Can you please assign this issue to me @lmas3009

**Comment by lmas3009** [comment] 2023-10-23 08:34
sure @Shreyaprasad02

**Comment by Shreyaprasad02** [comment] 2023-10-25 05:53
raised pr #239 @lmas3009 can you please review my pr

**Closed** 2024-10-02 11:33 UTC
Labels: good first issue, css, html, bootstrap, tailwindcss, hacktoberfest, hacktoberfest-accepted, hacktoberfest23
